// DO NOT DELETE THIS PAGE.
// This page is a showcase for UI components. It should be kept for reference.
import React, { useState } from 'react';
import { HelpCircle, Info, X, ChevronDown, ChevronUp } from 'lucide-react';
import './Showcase.css';

const HelpText = () => (
    <span>
        <strong>Why use this option?</strong><br />
        This option is useful when an attacker knows the maximum length of the passwords generated by this tool.
        <br /><br />
        If you systematically use the same length for a given service, enabling "Fuzz Length" allows you to vary
        the final length slightly to <em>blur the lines</em> and complicate statistical analysis.
    </span>
);

export const HelpShowcase = ({ onExit }) => {
    const [inlineOpen, setInlineOpen] = useState(false);
    const [popoverOpen, setPopoverOpen] = useState(false);

    return (
        <div className="showcase-container animate-fade-in">
            <div className="showcase-header">
                <button onClick={onExit} style={{ position: 'absolute', left: '2rem', top: '2rem', background: 'none', border: '1px solid rgba(255,255,255,0.2)', color: 'white', padding: '0.5rem 1rem', borderRadius: '8px', cursor: 'pointer' }}>
                    ← Back
                </button>
                <h1 className="showcase-title">Help UI Patterns</h1>
                <p style={{ color: '#94a3b8' }}>Demonstration of different contextual help styles</p>
            </div>

            <div className="showcase-grid">

                {/* Option 1: Hover Tooltip */}
                <div className="showcase-card">
                    <div className="card-title">
                        <span style={{ background: 'rgba(96, 165, 250, 0.2)', padding: '4px 8px', borderRadius: '4px', fontSize: '0.8em' }}>01</span>
                        Classic Hover
                    </div>
                    <p style={{ marginBottom: '1rem', fontSize: '0.9rem', color: '#94a3b8' }}>
                        Hover over the question mark. Ideal for quick, non-intrusive help.
                    </p>

                    <div className="control-row">
                        <span>Fuzz Length</span>
                        <div className="tooltip-wrapper">
                            <button className="help-trigger" aria-label="Help">
                                <HelpCircle size={20} />
                            </button>
                            <div className="tooltip-content">
                                <HelpText />
                            </div>
                        </div>
                    </div>
                </div>

                {/* Option 2: Inline Expandable */}
                <div className="showcase-card">
                    <div className="card-title">
                        <span style={{ background: 'rgba(167, 139, 250, 0.2)', padding: '4px 8px', borderRadius: '4px', fontSize: '0.8em' }}>02</span>
                        Inline Expand
                    </div>
                    <p style={{ marginBottom: '1rem', fontSize: '0.9rem', color: '#94a3b8' }}>
                        Click to expand the explanation. Ideal for long texts or on mobile.
                    </p>

                    <div className="control-row" style={{ flexDirection: 'column', alignItems: 'stretch', gap: 0 }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                            <span>Fuzz Length</span>
                            <button
                                className="help-trigger"
                                onClick={() => setInlineOpen(!inlineOpen)}
                                style={{ transform: inlineOpen ? 'rotate(180deg)' : 'rotate(0deg)' }}
                            >
                                {inlineOpen ? <ChevronUp size={20} /> : <HelpCircle size={20} />}
                            </button>
                        </div>

                        {inlineOpen && (
                            <div className="inline-help-panel animate-slide-down">
                                <HelpText />
                            </div>
                        )}
                    </div>
                </div>

                {/* Option 3: Glass Popover */}
                <div className="showcase-card">
                    <div className="card-title">
                        <span style={{ background: 'rgba(244, 114, 182, 0.2)', padding: '4px 8px', borderRadius: '4px', fontSize: '0.8em' }}>03</span>
                        Glass Popover
                    </div>
                    <p style={{ marginBottom: '1rem', fontSize: '0.9rem', color: '#94a3b8' }}>
                        Click to open a floating panel. "Premium" and modern style.
                    </p>

                    <div className="control-row popover-container">
                        <span>Fuzz Length</span>
                        <button
                            className={`help-trigger ${popoverOpen ? 'active' : ''}`}
                            onClick={() => setPopoverOpen(!popoverOpen)}
                        >
                            <Info size={20} />
                        </button>

                        {popoverOpen && (
                            <div className="glass-popover">
                                <button className="close-btn" onClick={() => setPopoverOpen(false)}>
                                    <X size={14} />
                                </button>
                                <h4 style={{ margin: '0 0 0.5rem 0', color: '#f472b6' }}>About Fuzz Length</h4>
                                <div style={{ fontSize: '0.85rem', lineHeight: '1.5', color: '#e2e8f0' }}>
                                    <HelpText />
                                </div>
                            </div>
                        )}
                    </div>
                </div>

            </div>
        </div>
    );
};
